- language: node_js
  node_js:
    - "8.0.0"
  before_install:
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
    - export PATH=$HOME/.yarn/bin:$PATH
  cache:
    yarn: true
  script:
    - yarn install
    - yarn build
  deploy:
    provider: pages
    local_dir: docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
      branch: master